; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
lib_deps = 
	; adafruit/Adafruit TinyUSB Library@3.3.1
	bodmer/TFT_eSPI@^2.5.43
monitor_speed = 115200
build_type = release
build_unflags = 
	-DARDUINO_USB_MODE=1
	-std=gnu++11
build_flags = 
	-std=gnu++2a
	${env.build_flags}
